DFT_TIME = '00'

DFT_DURATION = "00:00:05"
DFT_DURATION_VAL = 5.0
DFT_DURATION_TXT = "5 Seconds"

MAX_DURATION = "00:00:00"
MAX_DURATION_VAL = 59.0
MAX_DURATION_TXT = "WHOLE VIDEO"

DONATE_LINK = "https://www.paypal.com/donate/?hosted_button_id=RNDCMNV4YWHX4"
