APP_TITLE = 'Easy Gifer'
APP_THEME = "DarkBlue"
START_TOOLTIP = "Make a gif"
BROWSE_TOOLTIP = "Choose a video"
SELECT_VIDEO = 'Choose any video file to convert into a gif:'
TRIM = "Check to Trim"
START_AT = 'Start at:'
DURATION = 'Duration:'
SPEED_DISPLAY = '1.0x'
CHANGE_SPEED = 'Change speed:'
DEFAULT_DURATION = 'Whole Video'
